apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs-no-dockerfile-a8mz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs-no-dockerfile-a8mz
    app.kubernetes.io/part-of: test-app-rudi
  name: nodejs-no-dockerfile-a8mz
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: nodejs-no-dockerfile-a8mz
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: nodejs-no-dockerfile-a8mz
    spec:
      containers:
      - image: quay.io/susdas_quay_org/build-e2e-ishn-tenant/test-app-rudi/nodejs-no-dockerfile-a8mz@sha256:207174da06fd8d4b865b245aaf80d49a552516056565e8855451ce85f9c4ea99
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
